[[!getResources?
    &where=`{"template:=":14}`
    &parents=`1606`
    &tpl=`structure-employee`
    &tplWrapper=`collegue-panel-wrapper`
    &includeTVs=`1`
    &processTVs=`1`
    &sortby=`menuindex`
    &sortdir=`ASC`
    &depth=`1`
    &limit=`0`
]]

[[!getResources?
    &where=`{"template:=":8}`
    &parents=`[[*id]]`
    &tpl=`structure-boss`
    &includeTVs=`1`
    &sortby=`menuindex`
    &sortdir=`ASC`
    &depth=`1`
    &limit=`0`
]]

[[!getResources?
    &where=`{"template:=":18}`
    &parents=`135`
    &tpl=`structure-faculty`
    &includeTVs=`1`
    &sortby=`menuindex`
    &sortdir=`ASC`
    &depth=`1`
    &limit=`0`
]]
