[[!getResources?
    &where=`{"template:=":14}`
    &parents=`[[*id]]`
    &tpl=`structure-boss-only`
    &includeTVs=`1`
    &processTVs=`1`
    &sortby=`menuindex`
    &sortdir=`ASC`
    &depth=`1`
    &limit=`1`
]]

[[!getResources?
    &where=`{"template:=":8}`
    &parents=`[[*id]]`
    &tpl=`structure-boss`
    &includeTVs=`1`
    &sortby=`menuindex`
    &sortdir=`ASC`
    &depth=`1`
]]

[[!getResources?
    &where=`{"template:=":18}`
    &parents=`135`
    &tpl=`structure-faculty`
    &includeTVs=`1`
    &sortby=`menuindex`
    &sortdir=`ASC`
    &depth=`1`
]]